task: ISLR
data:
  model_name: UFOneView
  # Đường dẫn dữ liệu trên máy bạn
  base_url: "C:/Users/Duc Do/Downloads/M3-SLR/data/vsl"
  dataset_name: VN_SIGN
  temporal_stride: 2
  num_output_frames: 16
  crop_two_hand: False
  transform_cfg:
    index_setting:
      - segment #train_p
      - pad #train_m
      - segment #test_p
      - pad #test_m
  vid_transform:
    IMAGE_SIZE: 224
    NORM_MEAN_IMGNET: [0.485, 0.456, 0.406]
    NORM_STD_IMGNET: [0.229, 0.224, 0.225]
  SHOULDER_DIST_EPSILON: 1.2
  WRIST_DELTA: 0.15
  label_folder: label1-200/label/labelThreeView
  data_type: labels

training:
  test: true
  label_smoothing: 0
  device: cpu
  overwrite: true
  log_freq: 1
  experiment_name: "UsimKD MultiVSL200 (Testing on CPU)"
  model_dir: results/vn_sign
  random_seed: 42
  shuffle: True
  num_workers: 0
  prefetch_factor: 2
  batch_size: 1
  total_epoch: 300
  learning_rate: 0.0001
  save_checkpoints: true
  scheduler_factor: 0.1
  scheduler_patience: 5
  plot_loss: true
  plot_lr: true
  plot_acc: true
  criterion: MyCustomLoss
  optimzer: Adam
  lr_scheduler: StepLR
  top_k: 5
  print_stats: true
  pretrained: false
  # UsimKD sẽ dùng 2 checkpoint riêng trong thư mục gốc dự án
  pretrained_model: null
  lr_step_size: 10
  gamma: 0.8
  num_accumulation_steps: 4
  patience: 15
  verbose: true
  delta: 0
  is_early_stopping: true
  gradient_clip_val: 1
  w_decay: 1e-3
  log_train_step: true
  log_steps: 50
  evaluate_step: 250
  evaluate_strategy: epoch

model:
  num_classes: 199
  embed_size: 512
  # Quan trọng: Giữ nguyên lỗi chính tả 'pretraiend' của tác giả để code nhận diện
  pretraiend: True
  # Student checkpoint (one-view) sẽ được copy vào thư mục gốc M3-SLR
  pretrained_name: "cp_std.pth"
  # Teacher checkpoint (three-view) sẽ được copy vào thư mục gốc M3-SLR
  teacher_checkpoint: "cp_tec.pth"